// This file is automatically generated at startup. Do not modify.
import { genericFetch } from "./api_base";
export async function course(input: string): Promise<WithTucanUrlQ291cnNl> {
  return (await genericFetch(
    "http://localhost:8080/course",
    input
  )) as WithTucanUrlQ291cnNl;
}
export async function get_modules(
  input: string | null
): Promise<WithTucanUrlTW9kdWxlTWVudVJlc3BvbnNl> {
  return (await genericFetch(
    "http://localhost:8080/modules",
    input
  )) as WithTucanUrlTW9kdWxlTWVudVJlc3BvbnNl;
}
export async function index(input: null): Promise<string> {
  return (await genericFetch("http://localhost:8080/", input)) as string;
}
export async function login(input: Login): Promise<LoginResult> {
  return (await genericFetch(
    "http://localhost:8080/login",
    input
  )) as LoginResult;
}
export async function logout(input: null): Promise<null> {
  return (await genericFetch("http://localhost:8080/logout", input)) as null;
}
export async function module(
  input: string
): Promise<WithTucanUrlTW9kdWxlUmVzcG9uc2U> {
  return (await genericFetch(
    "http://localhost:8080/module",
    input
  )) as WithTucanUrlTW9kdWxlUmVzcG9uc2U;
}
export async function my_courses(
  input: null
): Promise<WithTucanUrlQ291cnNlW10> {
  return (await genericFetch(
    "http://localhost:8080/my_courses",
    input
  )) as WithTucanUrlQ291cnNlW10;
}
export async function my_modules(
  input: null
): Promise<WithTucanUrlTW9kdWxlW10> {
  return (await genericFetch(
    "http://localhost:8080/my_modules",
    input
  )) as WithTucanUrlTW9kdWxlW10;
}
export async function search_course(input: string): Promise<SearchResult[]> {
  return (await genericFetch(
    "http://localhost:8080/search-course",
    input
  )) as SearchResult[];
}
export async function search_module(input: string): Promise<SearchResult[]> {
  return (await genericFetch(
    "http://localhost:8080/search-module",
    input
  )) as SearchResult[];
}
export async function search_module_opensearch(
  input: string
): Promise<SearchResult[]> {
  return (await genericFetch(
    "http://localhost:8080/search-module-opensearch",
    input
  )) as SearchResult[];
}
export type Course = {
  tucan_id: string;
  tucan_last_checked: string;
  title: string;
  course_id: string;
  sws: number;
  content: string;
  done: boolean;
};
export type Login = {
  username: string;
  password: string;
};
export type LoginResult = {
  success: boolean;
};
export type Module = {
  tucan_id: string;
  tucan_last_checked: string;
  title: string;
  module_id: string;
  credits: number | null;
  content: string;
  done: boolean;
};
export type ModuleMenu = {
  tucan_id: string;
  tucan_last_checked: string;
  name: string;
  done: boolean;
  parent: string;
};
export type ModuleMenuPathPart = {
  parent: number[] | null;
  tucan_id: string;
  name: string;
  leaf: boolean;
};
export type ModuleMenuResponse = {
  module_menu: ModuleMenu;
  entries: Registration;
  path: ModuleMenuPathPart[][];
};
export type ModuleResponse = {
  module: Module;
  path: ModuleMenuPathPart[][];
};
export type Registration = {
  submenus: ModuleMenu[];
  modules_and_courses: [Module | null, Course[]][];
};
export type SearchResult = {
  tucan_id: string;
  title: string;
  excerpt: string;
  rank: number;
};
export type WithTucanUrlQ291cnNl = {
  tucan_url: string;
  inner: Course;
};
export type WithTucanUrlQ291cnNlW10 = {
  tucan_url: string;
  inner: Course[];
};
export type WithTucanUrlTW9kdWxlTWVudVJlc3BvbnNl = {
  tucan_url: string;
  inner: ModuleMenuResponse;
};
export type WithTucanUrlTW9kdWxlUmVzcG9uc2U = {
  tucan_url: string;
  inner: ModuleResponse;
};
export type WithTucanUrlTW9kdWxlW10 = {
  tucan_url: string;
  inner: Module[];
};
